--CREATE USER docker WITH PASSWORD 'docker';
CREATE USER docker;
CREATE DATABASE test_startup;
GRANT ALL PRIVILEGES ON DATABASE test_startup TO docker;

CREATE TABLE public.parent_groups (
    parent_group_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    parent_group text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    used_in_project boolean,
    CONSTRAINT pantent_gorups_pkey PRIMARY KEY (parent_group_id)
)

CREATE TABLE groups (
    parent_group_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    group_id character varying(20) COLLATE pg_catalog."default",
    group_name text,
    archetype character varying(256) COLLATE pg_catalog."default",
    current_status character varying(50) COLLATE pg_catalog."default",
    version_first_released character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT gorups_pkey PRIMARY KEY (parent_group_id)
)

CREATE TABLE loinc_terms (
    category character varying(256) COLLATE pg_catalog."default",
    group_id character varying(20) COLLATE pg_catalog."default",
    archetype character varying(256) COLLATE pg_catalog."default",
    loinc_code character varying(20) COLLATE pg_catalog."default",
    long_common_name text
)

CREATE TABLE loinc_terms_95percent (
    loinc_code character varying(20) COLLATE pg_catalog."default",
    long_common_name text,
    order_obs character varying(50) COLLATE pg_catalog."default"
)

CREATE TABLE raw_medical_data (
    chemical_name character varying(256) COLLATE pg_catalog."default",
    study_title text,
    accession_number character varying(100) COLLATE pg_catalog."default",
    depositor_study_number character varying(100) COLLATE pg_catalog."default",
    organization_name character varying(256) COLLATE pg_catalog."default",
    start_date character varying(100) COLLATE pg_catalog."default",
    end_date character varying(100) COLLATE pg_catalog."default",
    dose decimal(40,15),
    dose_unit character varying(50) COLLATE pg_catalog."default",
    ntp_toxicology_type character varying(100) COLLATE pg_catalog."default",
    ntp_tdms_number character varying(100) COLLATE pg_catalog."default",
    time_in_study integer,
    time_in_study_unit character varying(100) COLLATE pg_catalog."default",
    group_name character varying(100) COLLATE pg_catalog."default",
    is_control_group boolean,
    treatment_group_type character varying(100) COLLATE pg_catalog."default",
    route character varying(100) COLLATE pg_catalog."default",
    subject_name character varying(100) COLLATE pg_catalog."default",
    species_common_name character varying(100) COLLATE pg_catalog."default",
    sex character varying(100) COLLATE pg_catalog."default",
    strain character varying(100) COLLATE pg_catalog."default",
    ala decimal(40,15),
    ala_unit character varying(100) COLLATE pg_catalog."default",
    alp decimal(40,15),
    alp_unit character varying(20) COLLATE pg_catalog."default",
    alphr decimal(40,15),
    alphr_unit character varying(20) COLLATE pg_catalog."default",
    ap_creat decimal(40,15),
    ap_creat_unit character varying(20) COLLATE pg_catalog."default",
    asp_creat decimal(40,15),
    asp_creat_unit character varying(20) COLLATE pg_catalog."default",
    asp_hr decimal(40,15),
    asp_hr_unit character varying(20) COLLATE pg_catalog."default",
    ast decimal(40,15),
    ast_unit character varying(20) COLLATE pg_catalog."default",
    ava decimal(40,15),
    ava_unit character varying(20) COLLATE pg_catalog."default",
    bili decimal(40,15),
    bili_unit character varying(20) COLLATE pg_catalog."default",
    ca decimal(40,15),
    ca_unit character varying(20) COLLATE pg_catalog."default",
    cl decimal(40,15),
    cl_unit character varying(20) COLLATE pg_catalog."default",
    creat decimal(40,15),
    creat_unit character varying(20) COLLATE pg_catalog."default",
    creat_hr decimal(40,15),
    creat_hr_unit character varying(20) COLLATE pg_catalog."default",
    crtn_16 decimal(40,15),
    crtn_16_unit character varying(20) COLLATE pg_catalog."default",
    crtn_24 decimal(40,15),
    crtn_24_unit character varying(20) COLLATE pg_catalog."default",
    crtn_48 decimal(40,15),
    crtn_48_unit character varying(20) COLLATE pg_catalog."default",
    decalol decimal(40,15),
    decalol_unit character varying(20) COLLATE pg_catalog."default",
    galac decimal(40,15),
    galac_unit character varying(20) COLLATE pg_catalog."default",
    ggt decimal(40,15),
    ggt_unit character varying(20) COLLATE pg_catalog."default",
    ggt_creat decimal(40,15),
    ggt_creat_unit character varying(20) COLLATE pg_catalog."default",
    ggt_hr decimal(40,15),
    ggt_hr_unit character varying(20) COLLATE pg_catalog."default",
    gluc decimal(40,15),
    gluc_unit character varying(20) COLLATE pg_catalog."default",
    gluc_hr decimal(40,15),
    gluc_hr_unit character varying(20) COLLATE pg_catalog."default",
    glu_creat decimal(40,15),
    glu_creat_unit character varying(20) COLLATE pg_catalog."default",
    glu_hr_tis decimal(40,15),
    glu_hr_tis_unit character varying(20) COLLATE pg_catalog."default",
    k decimal(40,15),
    k_unit character varying(20) COLLATE pg_catalog."default",
    ketone decimal(40,15),
    ketone_unit character varying(20) COLLATE pg_catalog."default",
    ldh_creatn decimal(40,15),
    ldh_creatn_unit character varying(20) COLLATE pg_catalog."default",
    mg decimal(40,15),
    mg_unit character varying(20) COLLATE pg_catalog."default",
    na decimal(40,15),
    na_unit character varying(20) COLLATE pg_catalog."default",
    nag decimal(40,15),
    nag_unit character varying(20) COLLATE pg_catalog."default",
    nag_creat decimal(40,15),
    nag_creat_unit character varying(20) COLLATE pg_catalog."default",
    nag_hr decimal(40,15),
    nag_hr_unit character varying(20) COLLATE pg_catalog."default",
    ph decimal(40,15),
    ph_unit character varying(20) COLLATE pg_catalog."default",
    phos decimal(40,15),
    phos_unit character varying(20) COLLATE pg_catalog."default",
    protein decimal(40,15),
    protein_unit character varying(20) COLLATE pg_catalog."default",
    pro_creat decimal(40,15),
    pro_creat_unit character varying(20) COLLATE pg_catalog."default",
    pro_g_hr decimal(40,15),
    pro_g_hr_unit character varying(20) COLLATE pg_catalog."default",
    prpb decimal(40,15),
    prpb_unit character varying(20) COLLATE pg_catalog."default",
    prpb_hr decimal(40,15),
    prpb_hr_unit character varying(20) COLLATE pg_catalog."default",
    rnase decimal(40,15),
    rnase_unit character varying(20) COLLATE pg_catalog."default",
    sdh decimal(40,15),
    sdh_unit character varying(20) COLLATE pg_catalog."default",
    spgrav decimal(40,15),
    spgrav_unit character varying(20) COLLATE pg_catalog."default",
    tcn_lt decimal(40,15),
    tcn_lt_unit character varying(20) COLLATE pg_catalog."default",
    tsprot decimal(40,15),
    tsprot_unit character varying(20) COLLATE pg_catalog."default",
    ubgen decimal(40,15),
    ubgen_unit character varying(20) COLLATE pg_catalog."default",
    upro_crtn decimal(40,15),
    upro_crtn_unit character varying(20) COLLATE pg_catalog."default",
    urea_conc decimal(40,15),
    urea_conc_unit character varying(20) COLLATE pg_catalog."default",
    urea_hr decimal(40,15),
    urea_hr_unit character varying(20) COLLATE pg_catalog."default",
    urine_vol decimal(40,15),
    urine_vol_unit character varying(20) COLLATE pg_catalog."default",
    ur_bld character varying(100) COLLATE pg_catalog."default",,
    ur_bld_unit character varying(20) COLLATE pg_catalog."default",
    ur_clar character varying(20) COLLATE pg_catalog."default",
    ur_clar_unit character varying(20) COLLATE pg_catalog."default",
    ur_color character varying(100) COLLATE pg_catalog."default",
    ur_color_unit character varying(100) COLLATE pg_catalog."default",
    ur_prot decimal(40,15),
    ur_prot_unit character varying(20) COLLATE pg_catalog."default",
    ur_prot_hr decimal(40,15),
    ur_prot_hr_unit character varying(20) COLLATE pg_catalog."default",
    ur_vol_hr decimal(40,15),
    ur_vol_hr_unit character varying(20) COLLATE pg_catalog."default",
    cyto_rep character varying(256) COLLATE pg_catalog."default",
    cyto_rep_url character varying(512) COLLATE pg_catalog."default",
    amino character varying(256) COLLATE pg_catalog."default",
    amino_url character varying(512) COLLATE pg_catalog."default"
);

CREATE TABLE public.ordinal_value_sets (
    id serial,
    value_set_name character varying(256) COLLATE pg_catalog."default",
    loinc_code character varying(20) COLLATE pg_catalog."default",
    value_set_value character varying(256) COLLATE pg_catalog."default",
    sequence_number integer,
    CONSTRAINT ordinal_value_sets_pkey PRIMARY KEY (id)
);

--load data
COPY raw_medical_data(
	chemical_name,study_title,accession_number,depositor_study_number,organization_name,start_date,end_date,dose,dose_unit,ntp_toxicology_type,ntp_tdms_number,time_in_study,time_in_study_unit,group_name,is_control_group,treatment_group_type,route,subject_name,species_common_name,sex,strain,ala,ala_unit,alp,alp_unit,alphr,alphr_unit,ap_creat,ap_creat_unit,asp_creat,asp_creat_unit,asp_hr,asp_hr_unit,ast,ast_unit,ava,ava_unit,bili,bili_unit,ca,ca_unit,cl,cl_unit,creat,creat_unit,creat_hr,creat_hr_unit,crtn_16,crtn_16_unit,crtn_24,crtn_24_unit,crtn_48,crtn_48_unit,decalol,decalol_unit,galac,galac_unit,ggt,ggt_unit,ggt_creat,ggt_creat_unit,ggt_hr,ggt_hr_unit,gluc,gluc_unit,gluc_hr,gluc_hr_unit,glu_creat,glu_creat_unit,glu_hr_tis,glu_hr_tis_unit,k,k_unit,ketone,ketone_unit,ldh_creatn,ldh_creatn_unit,mg,mg_unit,na,na_unit,nag,nag_unit,nag_creat,nag_creat_unit,nag_hr,nag_hr_unit,ph,ph_unit,phos,phos_unit,protein,protein_unit,pro_creat,pro_creat_unit,pro_g_hr,pro_g_hr_unit,prpb,prpb_unit,prpb_hr,prpb_hr_unit,rnase,rnase_unit,sdh,sdh_unit,spgrav,spgrav_unit,tcn_lt,tcn_lt_unit,tsprot,tsprot_unit,ubgen,ubgen_unit,upro_crtn,upro_crtn_unit,urea_conc,urea_conc_unit,urea_hr,urea_hr_unit,urine_vol,urine_vol_unit,ur_bld,ur_bld_unit,ur_clar,ur_clar_unit,ur_color,ur_color_unit,ur_prot,ur_prot_unit,ur_prot_hr,ur_prot_hr_unit,ur_vol_hr,ur_vol_hr_unit,cyto_rep,cyto_rep_url,amino,amino_url
)
FROM '/tmp/raw_data.txt'
DELIMITER E'\t'
CSV HEADER;

